language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install python-software-properties
    - sudo apt-add-repository -y ppa:mosquitto-dev/mosquitto-ppa
    - sudo apt-get update -qq
    - sudo apt-get -y install mosquitto

before_script:
    - ./travis/compile-php.sh
    - ./travis/compile-ext.sh

script:
    - ./travis/run-tests.sh

